#!/usr/bin/env tsx
/**
 * Build src/index-wiki.md — a flat, machine-readable index of every wiki page.
 *
 * For each .md file under src/wiki/, emits one line:
 *   - [[title]] (path) — oneliner — tags: [...] — words: N — edited: YYYY-MM-DD
 *
 * Word count is computed from the body (excluding frontmatter).
 * Last edited prefers the file's git-tracked mtime, falling back to filesystem mtime.
 */
import { execFileSync } from "node:child_process"
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs"
import { join, relative, resolve } from "node:path"
import matter from "gray-matter"

const REPO_ROOT = resolve(new URL("..", import.meta.url).pathname)
const WIKI_DIR = join(REPO_ROOT, "src", "wiki")
const OUT_FILE = join(REPO_ROOT, "src", "index-wiki.md")

type Page = {
  title: string
  relPath: string
  oneliner: string
  tags: string[]
  words: number
  edited: string
}

function walkMd(dir: string): string[] {
  const out: string[] = []
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) out.push(...walkMd(full))
    else if (entry.isFile() && entry.name.endsWith(".md")) out.push(full)
  }
  return out
}

function lastEditedISO(file: string): string {
  try {
    const out = execFileSync("git", ["log", "-1", "--format=%cI", "--", file], {
      cwd: REPO_ROOT,
      stdio: ["ignore", "pipe", "ignore"],
    })
      .toString()
      .trim()
    if (out) return out.slice(0, 10)
  } catch {
    // not in git or git not available
  }
  return statSync(file).mtime.toISOString().slice(0, 10)
}

function countWords(body: string): number {
  return body
    .replace(/`{3}[\s\S]*?`{3}/g, " ") // code fences
    .replace(/`[^`]*`/g, " ") // inline code
    .replace(/!\[[^\]]*\]\([^)]*\)/g, " ") // images
    .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1") // links → text
    .replace(/[#>*_~\-]+/g, " ")
    .split(/\s+/)
    .filter(Boolean).length
}

const files = walkMd(WIKI_DIR).sort()
const pages: Page[] = files.map((file) => {
  const raw = readFileSync(file, "utf8")
  const { data, content } = matter(raw)
  return {
    title: typeof data.title === "string" ? data.title : relative(WIKI_DIR, file),
    relPath: relative(REPO_ROOT, file),
    oneliner: typeof data.oneliner === "string" ? data.oneliner : "",
    tags: Array.isArray(data.tags) ? data.tags.map(String) : [],
    words: countWords(content),
    edited: lastEditedISO(file),
  }
})

const missingOneliner = pages.filter((p) => !p.oneliner)
if (missingOneliner.length) {
  console.warn(
    `warn: ${missingOneliner.length} page(s) missing 'oneliner' frontmatter:\n  ` +
      missingOneliner.map((p) => p.relPath).join("\n  "),
  )
}

const lines: string[] = []
lines.push("---")
lines.push("title: Wiki Index")
lines.push(
  "oneliner: Machine-generated index of every wiki page; do not edit by hand. Run `npm run build-wiki-index`.",
)
lines.push("---")
lines.push("")
lines.push("<!-- Generated by cli/build-wiki-index.ts. Edits will be overwritten. -->")
lines.push("")
lines.push(
  `Generated ${new Date().toISOString().slice(0, 10)} from \`src/wiki/\`. ${pages.length} pages.`,
)
lines.push("")
for (const p of pages) {
  const tags = p.tags.length ? `[${p.tags.join(", ")}]` : "[]"
  const oneliner = p.oneliner || "_(missing oneliner)_"
  lines.push(
    `- **${p.title}** — \`${p.relPath}\` — ${oneliner} — tags: ${tags} — words: ${p.words} — edited: ${p.edited}`,
  )
}
lines.push("")

writeFileSync(OUT_FILE, lines.join("\n"))
console.log(`wrote ${relative(REPO_ROOT, OUT_FILE)} (${pages.length} pages)`)
